# .github/workflows/example.yml
name: Example Workflow

# Triggers the workflow on any push to the repository
on: [push]

jobs:
  build:
    # Specify the environment to run the job
    runs-on: ubuntu-latest

    steps:
      # Checkout the latest version of the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Run a simple shell command
      - name: Say Hello
        run: echo "Hello, MLOps!"
