# .github/workflows/train.yml
name: Train Model

# Trigger this workflow on push to the main branch
on:
  push:
    branches:
      - main

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
      # Checkout the latest code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python environment
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      # Install dependencies from requirements.txt
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Run the training script
      - name: Train the model
        run: python train.py

      # Save the trained model as an artifact
      - name: Upload model
        uses: actions/upload-artifact@v3
        with:
          name: model
          path: models/model.pkl
